added department permissions
nantonov/HRMS pull request #13
Opened 2021-08-23 14:22 UTC by VadimZharikov

- On get/{id} action adds the permission parameter

2021-08-24 13:02 UTC, nantonov approved these changes

2021-08-24 13:02 UTC, nantonov commented on HRMS/HRMS.WebApi/Controllers/EmployeesController.cs
> +            switch (employee.DepartmentId)
All business logic must be in the service

2021-08-24 13:02 UTC, nantonov commented on HRMS/HRMS.WebApi/Controllers/EmployeesController.cs
> +                        result.Add("Permissions", "Read, Write, Delete");
Please, use Enum instead of Strings

2021-08-24 13:05 UTC, nantonov requested changes
🔵

2021-08-24 21:29 UTC, VadimZharikov commented
- Excluded logic from controller

2021-08-25 10:33 UTC, nantonov requested changes

2021-08-25 10:33 UTC, nantonov commented on HRMS/HRMS.BLL/Entities/Employee.cs
> +        public IEnumerable<string> Permissions { get; set; }
Better to use IEnumerable of Enum with the same values

2021-08-25 13:04 UTC, VadimZharikov commented
Changed permissions property to Permissions enum type

2021-08-25 13:18 UTC, nantonov approved these changes

2021-08-25 14:41 UTC, merged